### ISSUE TITLE
use olive with ROS1 ?

### ISSUE THREAD

**Issue by mahammadirfan** [olive-robotics/olvx_playground_imu#1]
Hey i want to use the olive-imu with my ros1 platform ? do you have any support for ros1  ? and any more detailed ros support package for imu ?

Thanks

**Comment by cxdcxd** [comment]
@mahammadirfan, since the End of Life (EOL) for ROS Noetic is scheduled for 2025, we have decided to maintain ROS2 as our primary support platform. However, we will add native support for ROS1 in our upcoming updates. In the meantime, you can use a ROS2-ROS1 bridge to communicate with our IMU.

For more information, please refer to:

ROS2-ROS1 Bridge: [GitHub - ROS2/ROS1 Bridge](https://github.com/ros2/ros1_bridge)
Olive Robotics Documentation on ROS2 Bridge: [Olive Robotics - ROS/ROS2 Bridge Documentation](https://docs.olive-robotics.com/software/ros/ros2bridge.html)

**Comment by mahammadirfan** [comment]
@cxdcxd 
Hi, Thanks for your reply. That would be really helpful if you update ROS1 support.

Thanks

**Comment by mahammadirfan** [comment]
Hi @cxdcxd 
Our research group wants to use the Olive IMU...and we are working everything with ROS1(As we know ROS1 support gonna stop by 2025) still we can use ROS1.
As you mentioned to use Olive with ROS bridge...however it seems complicated to use....We are waiting ROS1 support from Olive teams.
Cheers!

**Comment by cxdcxd** [comment]
@mahammadirfan Thank you for your feedback. Sure, I will update you as soon as it is available.
